title: Silmood's room 
description: >
    Hi! **I am Peter**, software developer, super-amateur music producer, GDG Androidtitlan member and **the voice behind PodcastCompat**
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://silmood.github.io
disqus_shortname: silmood
facebook_username:
twitter_username: silmood
linkedin_username: pedro-antonio-hern√°ndez-a047759b
instagram_username:
pinterest_username:
flickr_username:
github_username: silmood
feed_icon: rss
email: silmood@protonmail.com
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
